# Generated by Django 4.0.4 on 2022-05-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0018_items_has_accepted_bid'),
        ('users', '0013_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('country_code', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.profiles')),
                ('country', models.CharField(max_length=50)),
                ('state_province_region', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.zip')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('sentdate', models.DateTimeField()),
                ('receiveddate', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.profiles')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.profiles')),
                ('shipping_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.shippinginformation')),
            ],
        ),
    ]
