# Generated by Django 4.0.4 on 2022-05-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginformation',
            name='city',
            field=models.CharField(default='Reykjavik', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='zip',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Zip',
        ),
    ]
