# Generated by Django 3.2.13 on 2022-05-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_address_shippinginformation_address_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orderdate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='receiveddate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='sentdate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shipping_info',
        ),
    ]
