# Generated by Django 4.0.4 on 2022-05-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biddate', models.DateField(auto_now=True)),
                ('bidamount', models.FloatField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiles')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
            ],
            options={
                'unique_together': {('bidder', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Accepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptdate', models.DateField(auto_now_add=True)),
                ('rating', models.FloatField()),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bids.bids')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profiles')),
            ],
        ),
    ]
