# Generated by Django 4.0.4 on 2022-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepts',
            name='acceptdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='biddate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
