# Generated by Django 4.0.4 on 2022-05-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_accepts_acceptdate_alter_bids_biddate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bids',
            unique_together=set(),
        ),
    ]
