# Generated by Django 4.0.4 on 2022-05-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_items_listdate'),
        ('users', '0012_alter_profiles_bio'),
        ('bids', '0003_alter_bids_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bids',
            unique_together={('bidder', 'item')},
        ),
    ]
