# Generated by Django 4.0.4 on 2022-05-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_itemimages_items_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.categories'),
        ),
    ]
