# Generated by Django 4.0.4 on 2022-05-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='no-image-default.png', upload_to='images/'),
        ),
    ]
