# Generated by Django 4.0.4 on 2022-05-04 22:41

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='no-image-default.png', upload_to=pathlib.PureWindowsPath('C:/Users/AraBu/Documents/HR/Verklegt2/VLN2_H55/Firesale/static/images')),
        ),
    ]
