# Generated by Django 4.0.4 on 2022-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='images/no-image-default.png', upload_to='images/'),
        ),
    ]
