# Generated by Django 4.0.4 on 2022-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='listdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
