# Generated by Django 3.2.13 on 2022-05-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_items_has_accepted_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='has_accepted_offer',
            new_name='has_accepted_bid',
        ),
    ]
