# Generated by Django 3.2.13 on 2022-05-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_rename_has_accepted_offer_items_has_accepted_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='has_accepted_bid',
        ),
    ]
