# Generated by Django 3.2.13 on 2022-05-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_remove_items_has_accepted_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='has_accepted_bid',
            field=models.BooleanField(default=False),
        ),
    ]
