# Generated by Django 4.0.4 on 2022-05-04 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_remove_profiles_email_remove_profiles_passwordhash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='online',
        ),
        migrations.AddField(
            model_name='profiles',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
