# Generated by Django 4.0.4 on 2022-05-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='images/'),
        ),
    ]
