# Generated by Django 4.0.4 on 2022-05-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_review_reviewed_alter_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='rated_by',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewed',
            new_name='rated_user',
        ),
    ]
