# Generated by Django 4.0.4 on 2022-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_review_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='get_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
