# Generated by Django 4.0.4 on 2022-05-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_ratings_rating'),
        ('users', '0018_profiles_get_notifications'),
    ]

    operations = [
    ]
