# Generated by Django 4.0.4 on 2022-05-13 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_uverifiedemails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UverifiedEmails',
            new_name='UnverifiedEmails',
        ),
    ]
